In [6]:
import numpy as np
'''Vectorization & Broadcasting'''

#Vectorization
arr = np.array([1, 2, 3, 4, 5])
#performing operations on vectors that are immediately compatible
sq_arr = arr ** 2   
print(sq_arr) 

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays, added element-wise ; same shape 


"""Broadcasting Rules:
1.Both arrays same shape 
2. If an array has 1 row or 1 column, it will be immediately
broadcasted under the hood"""

#Broadcasting
arr_mul10 = arr * 10    #10 will be stretched as an array of the same shape 
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)



[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]
